version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  target-branch: develop
  ignore:
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
  - dependency-name: org.mockito:mockito-junit-jupiter
    versions:
    - 3.7.0
    - 3.7.7
  - dependency-name: eu.benschroeder:mockito-extension
    versions:
    - 3.7.0
    - 3.7.7
