language: java
os: linux
dist: bionic

env:
  global:
  - secure: YKHSvjaMb2Hj0SUZhliYRfxPYZE4I6l2D3OVZXfZ2sG6L+7kCVsulafhZWTpyd6w9/cH+QHM1H1G3b43FYkTEluutWnHRSmqBNRRsl7s2spPM5+ZjQIbzJ75uxnSWXk3uvSYCBq5c7E7cwbHP6hxC6KjhEbC4ClILhCCmpYD06rT7+cUpSk+KmsSa61Pn6tO5fpAU3bNHO1i/tYSWP6wT1t38qudM0t3xW+V4j9JMj++ZKdd2PTedlUong9DLqxcwVhJDH+Mg2AZUAkYEB+O1S5Xh5yHEQOj+P8h1sbBL0R3282mxzevckEsCkx/mPpRMG4xSh4ShQGJro12iuBNFy8dEH7/pgVDcyy5CH/99Xo90h9+ULURfUi2suFCswO2tl0inVb/GY0mFzfv5Na8QrCfrLNq+h9T9v3tyo7Dyq8ogG8E8qk4lrl5MOmnhTtk9O2uykbGcZLXX3p8pRWLVstgUXLZMkJaVH1lBX4kpBhpPUkZ8pS8eF2MFyN1wBX3ZELiTBFbj8OTpZPU/b5XyX4DgvZZ1ALmGuM+G4iM83CYhxppARpRZSG6HJBVGTRSKSVQtdRdaQcetwXTfQSByaLmK4qcIwqqBoZkRRH97Petiy9aI5vuv00oLR7STCrvfCnA2J95KH9rTez1eMSt+UKOE7OIvpRxPlihJGs8XtY=
  - secure: QgMiLj+/UA9BZpwcXxxn9faG1pOOtupKtFA3mBBdzr6SPIBvHnMJRiCsIWqA9N0a1GS7rs3QVrnSaLA40g3bzh2DGumiLaVQ3lGmEFlMGhkClRed6dYrh7USVpxnm9AOfq1AvJbb588CKq8iYj/iENfh2U0xaBr6tkQ+BB2JFyp5YlTtYmeqkC3mjS/wcBNQ7xU839M6R0SHzAYGYqBEYyO71mbGo5YwTs7TtnZ11ygSaC4GeT4S9qNGnLw5NYnLzHsppBeLU1EjE5sBPX76NYwt7I4bC3OUOsEcD7GtCIZ4dBxG7RM5/PG/XifYMK4UKmGd5sZpX/njIUCxKwCow8Jar9FWJBRdTOfn//7gshMh3ULxalCu/29oUyk+9cCe7/KHGQ0INBLbM1jsU/6JKl0owTwWumfAIdgmWcSit5u+NxAX+hTz1spcq1U44ZxDQBBliaqdDYeA9W4R6OmD5jLsLVV6cFQlQWokbFqohN82mMhLRsr6HkYUYaicppMFbbAh+zXV9TDrPtgourgsBlwMApjl59w+85V/Bm8C9UdQqK41vpVD+MqigJnf4rhFvMr4DlPrdo8l8df7jWU1fhE6HrtwmAq/EbXXAk66nl7yJzdv6r/0vxJk4Vth6+xnjI0c5zt3zRqB2tNbDYn4ewDXBfdwsLL/Cknr5gbWZWg=
  - secure: x9+xeOpcrQkV3Pyg7aiP/LYIHvNCcIpeV251FrlJEA2HGdlTxujgQZwa0zt8HYitrEktAXHrUD4b+Ve/4I8KNpwDPbgKo6BiTaywci6som88AEF5AFsf6KAyG4i+q2gY9wuST5VhkJ8Lvt9wTNg36fx6HpGo9F2Up6HGl6gHfEicJSfqvy5s1Bb+RAwWYPDYr8BX0gWR6bNgOo1Bg4qpRol3r2cSUVlL/a6j1jXlOVbleFm/0O9MpiyzGmL+fiZ3op/kwIv641trm8mDmm0tenPOXkI4+TV2/CAS0nFPUEG3/JA3OC/FaG6JigSPloRNzXQb7KDknJZcpoIQRCnU2/1AQdfBNKEZamH/nUpY3heJ9wMNQSwayRhMBik37drtkDmMgwWJk4MffiKML2g3vXRx2M1sZhUAGRqThqXJFcNMfPHfqf0z5bc24fo/VLIxgjqkyW3ivaTLISDlXzwN11ZAsqXdMIRfJF1y1Wb4W9bXsernQ6E27hOdejgt4VXJiz4G87KtkDHeMrKUm3Ockx2VhfgnIjlNxz8garzcU4ZHVMj1hL1cLcaJ9TdqHqEu7nCnlD0mynBQPnPoawUlB0qaY6bQ9M8ajUqFdya91eNDOGhjoOLMWVcqeh4xmuH+o1cEulzska8S71iXL/Hh0qeBnlE9ZeGXEJ7ccIE9FMc=

cache:
  directories:
  - "$HOME/.m2"

jobs:
  include:
  - stage: build only
    if: branch != master AND tag IS blank
    before_install:
    - mvn clean dependency:go-offline --settings .maven.xml
    install:
    - mvn install --settings .maven.xml
  - stage: build AND use tag version AND deploy release
    if: tag IS present
    before_script:
    - mvn clean dependency:go-offline --settings .maven.xml
    - mvn versions:set -DgenerateBackupPoms=false -DnewVersion=$TRAVIS_TAG --settings .maven.xml
    - openssl aes-256-cbc -K $encrypted_33b8a3c18dee_key -iv $encrypted_33b8a3c18dee_iv
      -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d
    - gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --batch --import
      deployment/signingkey.asc
    - gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
      --batch --import deployment/signingkey.asc
    script:
    - mvn deploy --settings .maven.xml -Prelease -Dgpg.executable=gpg2 -Dgpg.keyname=E137DC17A85F039B
      -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg
      -Dgpg.passphrase=$PASSPHRASE
  - stage: build AND deploy snapshot
    if: branch = master
    before_script:
    - openssl aes-256-cbc -K $encrypted_33b8a3c18dee_key -iv $encrypted_33b8a3c18dee_iv
      -in deployment/signingkey.asc.enc -out deployment/signingkey.asc -d
    - gpg2 --keyring=$TRAVIS_BUILD_DIR/pubring.gpg --no-default-keyring --batch --import
      deployment/signingkey.asc
    - gpg2 --allow-secret-key-import --keyring=$TRAVIS_BUILD_DIR/secring.gpg --no-default-keyring
      --batch --import deployment/signingkey.asc
    script:
    - mvn deploy --settings .maven.xml -Prelease -Dgpg.executable=gpg2 -Dgpg.keyname=E137DC17A85F039B
      -Dgpg.publicKeyring=$TRAVIS_BUILD_DIR/pubring.gpg -Dgpg.secretKeyring=$TRAVIS_BUILD_DIR/secring.gpg
      -Dgpg.passphrase=$PASSPHRASE
